from pydantic import BaseModel, Field


class Source(BaseModel):
    chunk_index: int = Field(
        ...,
        description="Chunk used to generate the answer"
    )

    score: float = Field(
        ...,
        description="Similarity score of the retrieved chunk"
    )


class ChatResponse(BaseModel):
    answer: str = Field(
        ...,
        description="Answer generated by the AI"
    )

    sources: list[Source] = Field(
        default_factory=list,
        description="Chunks used while generating the answer"
    )