import json

from google.genai import types

from app.constants.rag import RAGConfig
from app.llm.gemini import client
from app.schemas.workflow import WorkflowPlan


class WorkflowAgent:
    """
    Agent 3.

    Converts structured document intelligence into
    an actionable workflow.

    Agent 3 does NOT independently analyze the document.

    It consumes the structured output produced by Agent 2.
    """

    def analyze(
        self,
        analysis: dict,
        objective: str,
    ) -> WorkflowPlan:

        prompt = self._build_prompt(
            analysis=analysis,
            objective=objective,
        )

        response = client.models.generate_content(
            model=RAGConfig.WORKFLOW_MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(
                temperature=0.1,
                max_output_tokens=RAGConfig.MAX_OUTPUT_TOKENS,
                response_mime_type="application/json",
                response_schema=WorkflowPlan,
            ),
        )

        if not response.text:
            raise RuntimeError(
                "Workflow Agent returned an empty response."
            )

        print("\n" + "=" * 70)
        print("WORKFLOW AGENT RAW RESPONSE")
        print("=" * 70)
        print(response.text)
        print("=" * 70)

        parsed = getattr(
            response,
            "parsed",
            None,
        )

        print(
            "PARSED RESPONSE:",
            parsed,
        )

        print("=" * 70)

        try:

            if parsed is not None:

                if isinstance(
                    parsed,
                    WorkflowPlan,
                ):
                    return parsed

                return WorkflowPlan.model_validate(
                    parsed
                )

            raw_text = response.text.strip()

            # Defensive handling for accidental markdown fences.
            if raw_text.startswith("```"):

                lines = raw_text.splitlines()

                if lines:
                    lines = lines[1:]

                if (
                    lines
                    and lines[-1].strip() == "```"
                ):
                    lines = lines[:-1]

                raw_text = "\n".join(
                    lines
                ).strip()

            data = json.loads(
                raw_text
            )

            return WorkflowPlan.model_validate(
                data
            )

        except json.JSONDecodeError as exc:

            print(
                "JSON PARSING FAILED:"
            )

            print(
                response.text
            )

            raise RuntimeError(
                "Workflow Agent returned invalid JSON."
            ) from exc

        except Exception as exc:

            print(
                "WORKFLOW SCHEMA VALIDATION FAILED:"
            )

            print(
                response.text
            )

            raise RuntimeError(
                "Workflow Agent returned an invalid workflow structure."
            ) from exc

    @staticmethod
    def _build_prompt(
        analysis: dict,
        objective: str,
    ) -> str:

        analysis_json = json.dumps(
            analysis,
            indent=2,
            ensure_ascii=False,
        )

        return f"""
You are an Enterprise AI Workflow Agent.

Your job is to convert structured document intelligence
into a practical and prioritized action plan.

You are NOT the primary document analyzer.

The supplied analysis was already generated by another
document intelligence agent.

Use ONLY the supplied analysis.

Never invent facts.

Never introduce external legal, financial, regulatory,
medical, or business requirements that are not supported
by the supplied analysis.

USER OBJECTIVE:
{objective}

STRUCTURED DOCUMENT ANALYSIS:
{analysis_json}

Determine:

1. Whether the objective can currently be completed.

2. What actions should happen immediately.

3. What actions should happen afterward.

4. What information should be monitored.

5. Which actions require human approval.

Prioritize actions using:

- critical
- high
- medium
- low

Use the following logic:

- Missing information blocking the objective → critical/high.
- High-severity risks affecting the objective → high.
- Important but non-blocking issues → medium.
- Informational follow-ups → low.

Every action must be grounded in the supplied analysis.

For every action provide:

- priority
- title
- action
- reason
- source
- evidence when available
- whether human approval is required

Do not provide explanations outside the structured response.

Return only the required workflow object.
"""